### ISSUE TITLE
Spelling mistakes in answers Caput 1 Pensum C

### ISSUE THREAD

**Issue by Carl393** [nktfh100/ExercitiaLatina#1]
Dear content creator. Can you make a flag whether it is est at the end of a sentence or not? Sometimes the question is marked wrong for this reason even If its right

Also you have made some typos in the answers caput 1 pensum C so that when the answers are revealed they are incorrect. This is a quick fix if you can manage it :-)

**Comment by Carl393** [comment]
More mistakes
See image, the section 7 of caput 1 the case shouldnt matter, also I think its helpful to change the word order to In arabia non multi fluvii sunt
![Screenshot_20210124-211351](https://user-images.githubusercontent.com/14049856/105653349-9c417c80-5e89-11eb-9b3d-467f25a70017.png)
![Screenshot_20210124-211645](https://user-images.githubusercontent.com/14049856/105653358-a3688a80-5e89-11eb-93c2-7d1fe0b623ba.png)

**Comment by nktfh100** [comment]
Hey, thanks for letting me know!
I have fixed the spelling mistakes

**Comment by Carl393** [comment]
Youre welcome! Any news on the word order of answers when they dont so much matter?

**Comment by Carl393** [comment]
Caput 2 exercise 11.. There seems to be a problem with the question...R est littera prima vocabuli primi? It should read P is littera prima vocabuli primi.... (I think this mistake is also in the exercise book!)

**Comment by nktfh100** [comment]
> Youre welcome! Any news on the word order of answers when they dont so much matter?

For questions like that I have to manually add multiple correct answers
And that is a lot of work, if you feel contributing that would be awesome!

**Comment by Carl393** [comment]
Sure I'm happy to help contribute to this project
If you want others to help correct or add content please join the Discord Server LLPSI there are a lot of people on there who are experts in Latin and would love to contribute as we use your web app almost exclusively for study groups.

Let me know how I can help contribute.

**Comment by nktfh100** [comment]
> Sure I'm happy to help contribute to this project
> If you want others to help correct or add content please join the Discord Server LLPSI there are a lot of people on there who are experts in Latin and would love to contribute as we use your web app almost exclusively for study groups.
> 
> Let me know how I can help contribute.
I am already in the latin discord server!
Well since my Latin is not the best there might be some mistakes in the pensa C (Since I had to type them myself)

**Comment by Carl393** [comment]
Capiulum 1 exercise 9.

can you remove the required period from the answer? people don't tend to think of inputting  a period when typing in a form.
![Screenshot 2021-01-30 3 16 03 PM](https://user-images.githubusercontent.com/14049856/106367098-49931500-630e-11eb-8239-8625defd28d2.png)
![Screenshot 2021-01-30 3 16 13 PM](https://user-images.githubusercontent.com/14049856/106367111-557ed700-630e-11eb-93c0-ef68ac9fd01c.png)

**Comment by nktfh100** [comment]
> Capiulum 1 exercise 9.
> 
> can you remove the required period from the answer? people don't tend to think of inputting a period when typing in a form.
> ![Screenshot 2021-01-30 3 16 03 PM](https://user-images.githubusercontent.com/14049856/106367098-49931500-630e-11eb-8239-8625defd28d2.png)
> ![Screenshot 2021-01-30 3 16 13 PM](https://user-images.githubusercontent.com/14049856/106367111-557ed700-630e-11eb-93c0-ef68ac9fd01c.png)

Of course.

**Comment by Carl393** [comment]
Thank you! Is it possible for "check answers" to be kept on when you go to the next exercise? it helps when you're doing a ton of questions in a row

**Comment by nktfh100** [comment]
> Thank you! Is it possible for "check answers" to be kept on when you go to the next exercise? it helps when you're doing a ton of questions in a row

Yeah that's actually a good idea!

**Comment by Carl393** [comment]
Hello Developer here's an unfinished question.
![Screenshot 2021-02-07 3 09 48 PM](https://user-images.githubusercontent.com/14049856/107158225-bafa4580-6956-11eb-9d39-4b85c6e80e2b.png)

**Comment by nktfh100** [comment]
> Hello Developer here's an unfinished question.
> ![Screenshot 2021-02-07 3 09 48 PM](https://user-images.githubusercontent.com/14049856/107158225-bafa4580-6956-11eb-9d39-4b85c6e80e2b.png)

Thanks, fixed!

**Comment by Carl393** [comment]
Caput V exercise 7 many typing mistakes

**Comment by nktfh100** [comment]
> Caput V exercise 7 many typing mistakes

Uh which questions?

**Comment by Carl393** [comment]
Thank you for fixing. Apparently there is another typo.
![Screenshot_20210215-150642](https://user-images.githubusercontent.com/14049856/107989159-a09c1980-6f9f-11eb-813c-9c98c1926e53.png)

**Comment by Carl393** [comment]
![Screenshot_20210215-151008](https://user-images.githubusercontent.com/14049856/107989308-0688a100-6fa0-11eb-9c74-1132b914a7ad.png)

**Comment by nktfh100** [comment]
> Thank you for fixing. Apparently there is another typo.
> ![Screenshot_20210215-150642](https://user-images.githubusercontent.com/14049856/107989159-a09c1980-6f9f-11eb-813c-9c98c1926e53.png)

Thanks, I fixed it

**Comment by Carl393** [comment]
Would you like an invite to join our discord server? everyone uses your website!
are you the original content creator? I have seen another website with this exact same type content (Without the check answers and it forces you to input macrons)

https://discord.gg/AUxcM3GV

**Comment by nktfh100** [comment]
> Would you like an invite to join our discord server? everyone uses your website!
> are you the original content creator? I have seen another website with this exact same type content (Without the check answers and it forces you to input macrons)
> 
> https://discord.gg/AUxcM3GV
> 
> your version is better however because you do not need to input macrons which I find annoying.

I would love to join!
Someone on reddit sent me their website that they couldn't host and I just copied the design

**Comment by Carl393** [comment]
Caput V exercise 1 many spelling errors
![Screenshot_20210308-205737](https://user-images.githubusercontent.com/14049856/110407066-3d0e8480-8051-11eb-935e-1e388c0421a1.png)

**Comment by Carl393** [comment]
Did someone else update the code recently? There are tons of spelling "autocorrected" errors all over the place on caput V.. This is very bad

**Comment by Carl393** [comment]
I beg your pardon, I think it might be in mobile mode the chrome browser attempts to automatically translate latin to the language it thinks it is (for me it was french) and attempts to translate it into english. Is it possible to add a note on the homepage warning people to disable auto translate webpages under the chrome settings? Otherwise you might have other confused people such as myself wondering why they are seeing english translations of Latin in strange places. Thank you
