### ISSUE TITLE
Chapter 5 - Pensum C - Minor Errors

### ISSUE THREAD

**Issue by Chromodyne** [nktfh100/ExercitiaLatina#14]
In CAPITVLUM V - PENSVM C there are various errors.

Q1: There is a missing macron on the 'i' in vīllā in the answer.

Q2: There are multiple errors.
     In the answer it should be " fīliōs " **not** " filōs " (Typo & macron error.)
     In the answer " filiam " should be "fīliam" (Macron error.)

**Comment by nktfh100** [comment]
Thank you!
