### ISSUE TITLE
errors in chapter 27, exercise 3

### ISSUE THREAD

**Issue by monstro1** [nktfh100/ExercitiaLatina#16]
The true answer to question 5 is written next to question 6. 6 next to 7, 7 next to 8, etc.

The answer to question 15
_Quotiēs in annō Aegyptiī metere possunt?_

from line 42 of the chapter:
_In Aegyptiī bis terve in annō metere possunt._

Also there's a missing macron in exercise 11, question 16. should be _videāminī_

**Comment by nktfh100** [comment]
Thanks!

**Comment by monstro1** [comment]
I think my answer is a little messed up actually, _Aegyptiī_ is in the genitive case. I kinda just assumed it was the ablative case for some reason (no clue why). It's kinda saying "In an Egyptian year..." so a better way to phrase the answer is probably

_In annō Aegyptiī bis terve metere possunt._

**Comment by nktfh100** [comment]
I see, thanks.
