### ISSUE TITLE
Mobile experience isn't great

### ISSUE THREAD

**Issue by pogotc** [nktfh100/ExercitiaLatina#2]
I've mostly been using this on my phone but there's a couple of minor issues I have, a couple of which can be seen in this screenshot:

<img src="https://user-images.githubusercontent.com/304623/108248932-5906c080-714c-11eb-8ff6-83d470625af5.jpeg" width="300" >

when you click on a textbox it kinda zooms in, which obscures the controls in the top right and also hides the next question. iOS is also doing something a bit weird with the size of the textbox. In the example the answer is "sunt", and the textbox width is 4 characters, but it doesn't seem to be enough, even though it's fine on desktop.

I'm actually quite happy to fix all this stuff myself and create a pull request, I found by tweaking the font-size of the text box it fixes the zoom issue, I also played around with re-styling the text box to just be an underline (this is how Duolingo and Babbel handle these kinds of questions).

The other idea I had was a button or something to take you to the get exercise instead of going through the menu, again, I'm happy to have a crack at making that change if you like?

**Comment by nktfh100** [comment]
Weird, I have been using it on android and its working fine.

And if you can improve this please do! :D

**Comment by pogotc** [comment]
> Weird, I have been using it on android and its working fine.
> 
> And if you can improve this please do! :D

Huh, must be an iPhone thing then? I've created my pull request and added some comments on the code so hopefully my changes all make sense. I don't have an android so I can't check I haven't broken it there, but I've tested it on desktop, iPhone, and the phone emulator mode in chrome and it all seems to work ok.

**Comment by nktfh100** [comment]
> > Weird, I have been using it on android and its working fine.
> > And if you can improve this please do! :D
> 
> Huh, must be an iPhone thing then? I've created my pull request and added some comments on the code so hopefully my changes all make sense. I don't have an android so I can't check I haven't broken it there, but I've tested it on desktop, iPhone, and the phone emulator mode in chrome and it all seems to work ok.

I merged the pull request, I have to say it looks way better now!
And it seems to be working fine on android

**Comment by pogotc** [comment]
Cool, glad to hear you're happy with the changes. Not sure if you have a wish list of ideas somewhere but I'd be happy to help more with the development of this, it's a fantastic app. From playing with a bit more yesterday a couple of things that I thought of that would be quite nice are:

1. Keeping track of your answers, could be useful if someone accidentally refreshes the page or even just so you know the next day where to carry on. I figured just putting this in localstorage is the simplest thing.
2. Some kind of hint or reveal single answer? I find myself sometimes wanting to see the answer for a single question as it'll get me on the right track for the remaining questions, but not wanting to see everything.

**Comment by nktfh100** [comment]
Great idea! I have implemented it so answers are now saved in localStorage.
You are welcome to implement your second idea if you want :)
(or any other good ideas you have)

**Comment by pogotc** [comment]
Fantastic, just had a quick play and the localStorage update seems to be working really well. I'll have a think and tinker with the hint / reveal answer idea, I don't want to just dump a load of extra buttons on the page as it'll look messy. But if I think of something I'll put a pull request in :)

I'll also close this issue to avoid cluttering up github

**Comment by Carl393** [comment]
Many spelling goofs since the mobile update...that were autocorrected to english....can you please fix

**Comment by pogotc** [comment]
Can you provide a bit more information or some examples of what you mean?
