### ISSUE TITLE
Chap 25, Exercise 2 brings up a blank screen

### ISSUE THREAD

**Issue by monstro1** [nktfh100/ExercitiaLatina#8]
Illud exercitium vidēre nōn possum.

When I pull up that exercise in particular, it brings up a blank white screen.

**Comment by nktfh100** [comment]
It seems like there is no answer to the fourth question
("4. Quem Rōmulus interfēcit?")
Do you by any chance know the answer to this question?

**Comment by monstro1** [comment]
> It seems like there is no answer to the fourth question
> ("4. Quem Rōmulus interfēcit?")
> Do you by any chance know the answer to this question?

Rōmulus Remum frātrem interfēcit.

from line 14 of the chapter

**Comment by nktfh100** [comment]
Thanks, I have fixed it.

**Comment by monstro1** [comment]
> Thanks, I have fixed it.

I just noticed, I think you accidentally skipped a question when initially writing the page. Since the true answer to question 5 is written next to answer 6. True answer to 6 next to 7, etc. This starts with question 5

the answer to the last question, in case you need it, is "Nāvis vēla ātra gerēbat."

**Comment by nktfh100** [comment]
Thanks, fixed as well.
